# Generated by Django 5.2.4 on 2026-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='access_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
