# Generated by Django 5.2.4 on 2026-07-31 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0005_deployment_deceased_age_deployment_deceased_name'),
        ('donors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='deployments.deployment'),
        ),
    ]
