# Generated by Django 5.2.4 on 2026-07-31 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donor_deployment'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='events.event'),
        ),
    ]
