# Generated by Django 5.2.4 on 2026-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donor_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='operator_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
