# Generated by Django 5.2.4 on 2026-09-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_alter_donor_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='status',
            field=models.CharField(default='RECORDED', max_length=50),
        ),
    ]
