# Generated by Django 5.2.4 on 2026-09-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_normalise_donor_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['date', 'time', 'id']},
        ),
    ]
