# Generated by Django 5.2.4 on 2026-07-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_code', models.CharField(max_length=50, unique=True)),
                ('representative_name', models.CharField(max_length=200)),
                ('number_of_people', models.IntegerField()),
                ('voucher_type', models.CharField(choices=[('full_meal', 'Full Meal'), ('drinks_only', 'Drinks Only'), ('snacks_only', 'Snacks Only')], max_length=50)),
                ('event_day', models.IntegerField()),
                ('time', models.TimeField()),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
