# Generated by Django 5.2.4 on 2026-08-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0005_chit_operator_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chit',
            name='voucher_type',
            field=models.CharField(choices=[('full_package', 'Full Package'), ('water_only', 'Water Only'), ('drink_only', 'Drink Only'), ('drinks_water', 'Drinks & Water'), ('food_water', 'Food & Water'), ('food_drinks', 'Food & Drinks')], max_length=50),
        ),
    ]
