# Generated by Django 5.2.4 on 2026-09-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0006_alter_chit_voucher_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chit',
            options={'ordering': ['date', 'time', 'id']},
        ),
    ]
