# Generated by Django 5.2.4 on 2026-09-27 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chits', '0007_alter_chit_options'),
        ('deployments', '0009_remove_deployment_title'),
        ('events', '0002_alter_event_access_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chit',
            options={'ordering': ['entry_number', 'id']},
        ),
        migrations.AddField(
            model_name='chit',
            name='entry_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Permanent per-event position in the ledger, assigned on create.', null=True),
        ),
        migrations.AddConstraint(
            model_name='chit',
            constraint=models.UniqueConstraint(fields=('event', 'entry_number'), name='unique_chit_entry_number_per_event'),
        ),
    ]
