# Generated by Django 5.2.4 on 2026-09-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='spent_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
