# Generated by Django 5.2.4 on 2026-07-30 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0002_initial'),
        ('deployments', '0002_sessiontimer'),
    ]

    operations = [
    ]
