# Generated by Django 5.2.4 on 2026-07-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0003_merge_0002_initial_0002_sessiontimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deceased_image',
            field=models.ImageField(blank=True, null=True, upload_to='deceased_images/'),
        ),
    ]
