# Generated by Django 5.2.4 on 2026-07-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0004_deployment_deceased_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='deceased_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deceased_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
