# Generated by Django 5.2.4 on 2026-07-31 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0006_backup'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='events.event'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='events.event'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hardware', to='events.event'),
        ),
        migrations.AddField(
            model_name='sessiontimer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_timers', to='events.event'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='deployment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.deployment'),
        ),
    ]
