# Generated by Django 5.2.4 on 2026-07-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0007_backup_event_deployment_event_hardware_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='deceased_age',
        ),
        migrations.AddField(
            model_name='deployment',
            name='year_of_birth',
            field=models.PositiveIntegerField(blank=True, help_text='Year of birth (e.g., 1980)', null=True),
        ),
    ]
