# Generated by Django 5.2.4 on 2026-08-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0008_remove_deployment_deceased_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='title',
        ),
    ]
