# Generated by Django 5.2.4 on 2026-07-29 18:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_temp_login',
            new_name='is_using_fallback',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 29, 18, 38, 10, 595951, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'System Owner'), ('family_head', 'Family Head'), ('chit_staff', 'Chit Staff'), ('donation_staff', 'Donation Staff')], default='donation_staff', max_length=20),
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hired_start_date', models.DateTimeField()),
                ('hired_duration_days', models.IntegerField()),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('locked', 'Locked')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.tenant'),
        ),
        migrations.CreateModel(
            name='TenantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('family_dashboard', 'Family Dashboard'), ('chit_console', 'Chit Console'), ('donation_portal', 'Donation Portal')], max_length=50)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('fallback_username', models.CharField(blank=True, max_length=150)),
                ('fallback_password_hash', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credentials', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Credential',
                'verbose_name_plural': 'Tenant Credentials',
                'unique_together': {('tenant', 'credential_type')},
            },
        ),
    ]
