# Generated by Django 5.2.4 on 2026-07-30 08:02

from django.db import migrations, models


def create_initial_credentials(apps, schema_editor):
    Credential = apps.get_model('users', 'Credential')
    
    # Create initial credential entries if they don't exist
    credentials = [
        {
            'credential_type': 'client',
            'username': '',
            'password_hash': '',
            'desk_operator_name': '',
            'temp_login': True,
            'session_expired': False,
        },
        {
            'credential_type': 'desk_operator',
            'username': '',
            'password_hash': '',
            'desk_operator_name': 'Samuel Adjetey',
            'temp_login': True,
            'session_expired': False,
        },
        {
            'credential_type': 'master_fallback',
            'username': '',
            'password_hash': '',
            'desk_operator_name': '',
            'temp_login': True,
            'session_expired': False,
        },
    ]
    
    for cred_data in credentials:
        Credential.objects.create(**cred_data)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('client', 'Client'), ('desk_operator', 'Desk Operator'), ('master_fallback', 'Master Fallback')], max_length=20, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('password_hash', models.CharField(max_length=255)),
                ('desk_operator_name', models.CharField(blank=True, max_length=150, null=True)),
                ('temp_login', models.BooleanField(default=True)),
                ('session_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'System Owner'), ('client', 'Client'), ('chit_staff', 'Chit Staff'), ('donation_staff', 'Donation Staff')], default='donation_staff', max_length=20),
        ),
        migrations.RunPython(create_initial_credentials),
    ]
