# Generated by Django 5.2.4 on 2026-07-30 08:09

from django.db import migrations


def create_initial_credentials(apps, schema_editor):
    Credential = apps.get_model('users', 'Credential')
    
    # Create initial credential entries if they don't exist
    credentials = [
        {
            'credential_type': 'client',
            'username': '',
            'password_hash': '',
            'desk_operator_name': '',
            'temp_login': True,
            'session_expired': False,
        },
        {
            'credential_type': 'desk_operator',
            'username': '',
            'password_hash': '',
            'desk_operator_name': 'Samuel Adjetey',
            'temp_login': True,
            'session_expired': False,
        },
        {
            'credential_type': 'master_fallback',
            'username': '',
            'password_hash': '',
            'desk_operator_name': '',
            'temp_login': True,
            'session_expired': False,
        },
    ]
    
    for cred_data in credentials:
        Credential.objects.create(**cred_data)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_credential_and_client_role'),
    ]

    operations = [
        migrations.RunPython(create_initial_credentials),
    ]
