# Generated by Django 5.2.4 on 2026-07-31 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20260730_0809'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                DROP TABLE IF EXISTS users_tenant CASCADE;
                DROP TABLE IF EXISTS users_tenantcredential CASCADE;
                ALTER TABLE users_user DROP COLUMN IF EXISTS tenant;
                ALTER TABLE users_user DROP COLUMN IF EXISTS email;
                ALTER TABLE users_user DROP COLUMN IF EXISTS first_name;
                ALTER TABLE users_user DROP COLUMN IF EXISTS last_name;
                ALTER TABLE users_user DROP COLUMN IF EXISTS is_using_fallback;
            ''',
            state_operations=[
                migrations.RemoveField(
                    model_name='user',
                    name='tenant',
                ),
                migrations.AlterUniqueTogether(
                    name='tenantcredential',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='tenantcredential',
                    name='tenant',
                ),
                migrations.RemoveField(
                    model_name='tenantcredential',
                    name='created_by',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='email',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='first_name',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='is_using_fallback',
                ),
                migrations.RemoveField(
                    model_name='user',
                    name='last_name',
                ),
                migrations.DeleteModel(
                    name='Tenant',
                ),
                migrations.DeleteModel(
                    name='TenantCredential',
                ),
            ],
        ),
    ]
