# Generated by Django 5.2.4 on 2026-07-31 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0007_remove_user_tenant_remove_tenantcredential_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='events.event'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='events.event'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='credential_type',
            field=models.CharField(choices=[('client', 'Client'), ('desk_operator', 'Desk Operator'), ('master_fallback', 'Master Fallback')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('credential_type', 'event')},
        ),
    ]
